### ISSUE TITLE
pip install pyhash failed

### ISSUE THREAD

**Issue by generall** [flier/pyfasthash#26]
```
Collecting pyhash
  Downloading https://files.pythonhosted.org/packages/fa/5e/2a9cfee0e8688ca1dccdf2a7690beda88089091eb0d9511beb73a2b63c9a/pyhash-0.9.0.tar.gz (517kB)
    100% |████████████████████████████████| 522kB 18.6MB/s ta 0:00:01
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-y_v8m3s3/pyhash/setup.py", line 8, in <module>
        from setuptools.glob import glob
    ModuleNotFoundError: No module named 'setuptools.glob'
```

**Comment by flier** [comment]
oops, seems your `setuptools` too old, please try to upgrade it with pip.

```
$ pip install --upgrade setuptools pip
``` 

maybe we can use system `glob` module instead of `setuptools.glob` later

**Comment by flier** [comment]
please try install the latest version, [0.9.1](https://pypi.org/project/pyhash/)
