### ISSUE TITLE
Illegal instruction (core dumped) on docker

### ISSUE THREAD

**Issue by jobevers** [flier/pyfasthash#30]
pyhash crashes when run under python 3.7 on docker:

To re-create:

```
docker run -it --rm python:3.7 /bin/bash
[...]
root@16cdfff1b7c4:/# python
Python 3.7.1 (default, Nov 16 2018, 06:19:57) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
root@16cdfff1b7c4:/# python -m pip install pyhash
Collecting pyhash
  Downloading https://files.pythonhosted.org/packages/55/61/56af3d9ab410b0f73a1a38cf8a93f656ee9937d59c7074a3afa5edbd6008/pyhash-0.9.1.tar.gz (594kB)
    100% |████████████████████████████████| 604kB 13.7MB/s 
Building wheels for collected packages: pyhash
  Running setup.py bdist_wheel for pyhash ... done
  Stored in directory: /root/.cache/pip/wheels/0a/dd/92/06521a3888c2b46df4a189f3458a78de4d769764f2a5ec639d
Successfully built pyhash
Installing collected packages: pyhash
Successfully installed pyhash-0.9.1
root@16cdfff1b7c4:/# python -m pyhash
Illegal instruction (core dumped)
```

**Comment by flier** [comment]
can you upload the core dump file or call stack?

**Comment by dvhh** [comment]
pyhash-0.9.3

GDB Error
```
Program received signal SIGILL, Illegal instruction.
pybind11::detail::get_internals () at src/pybind11/include/pybind11/detail/internals.h:94
94      src/pybind11/include/pybind11/detail/internals.h: No such file or directory.
```
Backtrace
```
#0  pybind11::detail::get_internals () at src/pybind11/include/pybind11/detail/internals.h:94
#1  0x00007ffff630978a in pybind11::detail::get_global_type_info (tp=...) at src/pybind11/include/pybind11/cast.h:178
#2  pybind11::detail::generic_type::initialize (this=this@entry=0x7fffffffb160, rec=...) at src/pybind11/include/pybind11/pybind11.h:889
#3  0x00007ffff6309c9f in pybind11::class_<fnv_t<unsigned int, true>>::class_<>(pybind11::handle, char const*) (name=0x7ffff634d70e "fnv1_32", scope=...,
    this=0x7fffffffb160) at src/pybind11/include/pybind11/pybind11.h:1083
#4  Hasher<fnv_t<unsigned int, true>, unsigned int, unsigned int>::Export (m=..., name=name@entry=0x7ffff634d70e "fnv1_32") at src/Hash.h:124
#5  0x00007ffff62f01fe in pybind11_init__pyhash (m=...) at src/Hash.cpp:27
#6  PyInit__pyhash () at src/Hash.cpp:17
#7  0x00000000005fb4ec in _PyImport_LoadDynamicModuleWithSpec (
    spec=<ModuleSpec(name='_pyhash', loader=<ExtensionFileLoader(name='_pyhash', path='<HOME>/.local/lib/python3.6/site-packages/_pyhash.cpython-36m-x86_64-linux-gnu.so') at remote 0x7ffff68354e0>, origin='<HOME>/.local/lib/python3.6/site-packages/_pyhash.cpython-36m-x86_64-linux-gnu.so', loader_state=None, submodule_search_locations=None, _set_fileattr=True, _cached=None) at remote 0x7ffff65a42e8>, fp=<optimized out>) at ../Python/importdl.c:159
#8  0x00000000005fb768 in _imp_create_dynamic_impl (module=<optimized out>, file=0x0,
    spec=<ModuleSpec(name='_pyhash', loader=<ExtensionFileLoader(name='_pyhash', path='<HOME>/.local/lib/python3.6/site-packages/_pyhash.cpython-36m-x86_64-linux-gnu.so') at remote 0x7ffff68354e0>, origin='<HOME>/.local/lib/python3.6/site-packages/_pyhash.cpython-36m-x86_64-linux-gnu.so', loader_state=None, submodule_search_locations=None, _set_fileattr=True, _cached=None) at remote 0x7ffff65a42e8>) at ../Python/import.c:1994
#9  _imp_create_dynamic (module=<optimized out>, args=<optimized out>) at ../Python/clinic/import.c.h:289
#10 0x000000000056617e in PyCFunction_Call (func=<built-in method create_dynamic of module object at remote 0x7ffff7f944f8>, args=<optimized out>,
    kwds=<optimized out>) at ../Objects/methodobject.c:112
#11 0x000000000050bb66 in do_call_core (kwdict={},
    callargs=(<ModuleSpec(name='_pyhash', loader=<ExtensionFileLoader(name='_pyhash', path='<HOME>/.local/lib/python3.6/site-packages/_pyhash.cpython-36m-x86_64-linux-gnu.so') at remote 0x7ffff68354e0>, origin='<HOME>/.local/lib/python3.6/site-packages/_pyhash.cpython-36m-x86_64-linux-gnu.so', loader_state=None, submodule_search_locations=None, _set_fileattr=True, _cached=None) at remote 0x7ffff65a42e8>,),
    func=<built-in method create_dynamic of module object at remote 0x7ffff7f944f8>) at ../Python/ceval.c:5102
#12 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:3404
#13 0x0000000000504c28 in PyEval_EvalFrameEx (throwflag=0,
    f=Frame 0x7ffff656c048, for file <frozen importlib._bootstrap>, line 219, in _call_with_frames_removed (f=<built-in method create_dynamic of module object at remote 0x7ffff7f944f8>, args=(<ModuleSpec(name='_pyhash', loader=<ExtensionFileLoader(name='_pyhash', path='/home/huy/.local/lib/python3.6/site-packages/_pyhash.cpython-36m-x86_64-linux-gnu.so') at remote 0x7ffff68354e0>, origin='/home/huy/.local/lib/python3.6/site-packages/_pyhash.cpython-36m-x86_64-linux-gnu.so', loader_state=None, submodule_search_locations=None, _set_fileattr=True, _cached=None) at remote 0x7ffff65a42e8>,), kwds={})) at ../Python/ceval.c:4166
....
```

tried rebuilding the binary via (same error)
```
pip install --user --force-reinstall --ignore-installed --no-binary :all: pyhash
```

**Comment by kingo55** [comment]
I'm getting the same error when I run it through gdb. Not using pyhash in Docker here (Not that I imagine it should be any different). I'm on Linux 5.2.9, Python 3.7.4 with pyhash 0.9.3:

```
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
pybind11::detail::internals::internals (this=0x55555562ca30) at src/pybind11/include/pybind11/detail/internals.h:94
94      src/pybind11/include/pybind11/detail/internals.h: No such file or directory.
```

Anytime I try to import it, Python returns:

```
illegal hardware instruction (core dumped)  python -m pyhash
```

**Comment by scattym** [comment]
Hi,

I believe I am getting the same error. My env is:
Ubuntu 19.10
Python 3.7.4 through pyenv
CPU: Intel I7-2600

When importing I get:
$ python -c 'import pyhash'
Illegal instruction (core dumped)

pyhash 0.9.3 and also when installing from source on 0.9.4.
Tried all 0.9.X versions
```
Program received signal SIGILL, Illegal instruction.
pybind11::detail::internals::internals (this=0x555555d7c470) at src/pybind11/include/pybind11/detail/internals.h:94
94      struct internals {
(gdb) bt
#0  pybind11::detail::internals::internals (this=0x555555d7c470) at src/pybind11/include/pybind11/detail/internals.h:94
#1  pybind11::detail::get_internals () at src/pybind11/include/pybind11/detail/internals.h:94
#2  0x00007ffff5198cd3 in pybind11::detail::get_global_type_info (tp=...) at src/pybind11/include/pybind11/cast.h:178
#3  pybind11::detail::generic_type::initialize (this=this@entry=0x7fffffffa650, rec=...) at src/pybind11/include/pybind11/pybind11.h:897
#4  0x00007ffff51997cf in pybind11::class_<fnv_t<unsigned int, true>>::class_<>(pybind11::handle, char const*) (name=0x7ffff520555c "fnv1_32", scope=..., this=0x7fffffffa650) at src/pybind11/include/pybind11/attr.h:463
#5  Hasher<fnv_t<unsigned int, true>, unsigned int, unsigned int>::Export (m=..., name=name@entry=0x7ffff520555c "fnv1_32") at src/Hash.h:124
#6  0x00007ffff517ebb7 in pybind11_init__pyhash (m=...) at src/Hash.cpp:32
#7  0x00007ffff51801f5 in PyInit__pyhash () at src/Hash.cpp:16
#8  0x0000555555696f61 in _PyImport_LoadDynamicModuleWithSpec (spec=spec@entry=0x7ffff6b85710, fp=fp@entry=0x0) at ./Python/importdl.c:159
#9  0x0000555555694beb in _imp_create_dynamic_impl (module=<optimised out>, file=<optimised out>, spec=0x7ffff6b85710) at Python/import.c:2167
#10 _imp_create_dynamic (module=<optimised out>, args=<optimised out>, nargs=<optimised out>) at Python/clinic/import.c.h:289
#11 0x00005555555ca9ac in _PyMethodDef_RawFastCallDict (method=0x555555838a40 <imp_methods+320>, self=0x7ffff7906cb0, args=0x7ffff69bcf68, nargs=1, kwargs=0x7ffff6b7ad20) at Objects/call.c:530
#12 0x00005555555cac06 in _PyCFunction_FastCallDict (kwargs=<optimised out>, nargs=<optimised out>, args=<optimised out>, func=0x7ffff791f7d0) at Objects/call.c:586
#13 PyCFunction_Call (kwargs=<optimised out>, args=<optimised out>, func=0x7ffff791f7d0) at Objects/call.c:791
#14 PyCFunction_Call (func=0x7ffff791f7d0, args=<optimised out>, kwargs=<optimised out>) at Objects/call.c:782
#15 0x00005555555b8225 in do_call_core (kwdict=0x7ffff6b7ad20, callargs=0x7ffff69bcf50, func=0x7ffff791f7d0) at Python/ceval.c:4641
#16 _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3191
#17 0x00005555556773f0 in PyEval_EvalFrameEx (throwflag=0, f=0x7ffff57db810) at Python/ceval.c:547
#18 _PyEval_EvalCodeWithName (_co=_co@entry=0x7ffff790e150, globals=<optimised out>, locals=locals@entry=0x0, args=args@entry=0x7ffff77d8e90, argcount=2, kwnames=0x0, kwargs=0x7ffff77d8ea0, kwcount=0, kwstep=1, defs=0x0, defcount=0, 
    kwdefs=0x0, closure=0x0, name=0x7ffff790c300, qualname=0x7ffff790c300) at Python/ceval.c:3930
#19 0x00005555555c9c2d in _PyFunction_FastCallKeywords (func=<optimised out>, stack=0x7ffff77d8e90, nargs=<optimised out>, kwnames=<optimised out>) at Objects/call.c:433
#20 0x00005555555aff75 in call_function (pp_stack=pp_stack@entry=0x7fffffffad30, oparg=<optimised out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4616
#21 0x00005555555b5dbb in _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3093
#22 0x00005555555aecd3 in function_code_fastcall (co=<optimised out>, args=<optimised out>, nargs=2, globals=<optimised out>) at Objects/call.c:283
#23 0x00005555555c9d42 in _PyFunction_FastCallKeywords (func=<optimised out>, stack=<optimised out>, nargs=<optimised out>, kwnames=<optimised out>) at Objects/call.c:415
#24 0x00005555555aff75 in call_function (pp_stack=pp_stack@entry=0x7fffffffaf10, oparg=<optimised out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4616
#25 0x00005555555b119c in _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3110
#26 0x00005555555aecd3 in function_code_fastcall (co=<optimised out>, args=<optimised out>, nargs=1, globals=<optimised out>) at Objects/call.c:283
#27 0x00005555555c9d42 in _PyFunction_FastCallKeywords (func=<optimised out>, stack=<optimised out>, nargs=<optimised out>, kwnames=<optimised out>) at Objects/call.c:415
#28 0x00005555555aff75 in call_function (pp_stack=pp_stack@entry=0x7fffffffb0f8, oparg=<optimised out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4616
#29 0x00005555555b2ac9 in _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3124
#30 0x00005555555aecd3 in function_code_fastcall (co=<optimised out>, args=<optimised out>, nargs=1, globals=<optimised out>) at Objects/call.c:283
#31 0x00005555555c9d42 in _PyFunction_FastCallKeywords (func=<optimised out>, stack=<optimised out>, nargs=<optimised out>, kwnames=<optimised out>) at Objects/call.c:415
#32 0x00005555555aff75 in call_function (pp_stack=pp_stack@entry=0x7fffffffb2d8, oparg=<optimised out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4616
#33 0x00005555555b2ac9 in _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3124
#34 0x00005555555aecd3 in function_code_fastcall (co=<optimised out>, args=<optimised out>, nargs=2, globals=<optimised out>) at Objects/call.c:283
#35 0x00005555555c9d42 in _PyFunction_FastCallKeywords (func=<optimised out>, stack=<optimised out>, nargs=<optimised out>, kwnames=<optimised out>) at Objects/call.c:415
#36 0x00005555555aff75 in call_function (pp_stack=pp_stack@entry=0x7fffffffb4b8, oparg=<optimised out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4616
#37 0x00005555555b2ac9 in _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3124
#38 0x00005555555aecd3 in function_code_fastcall (co=co@entry=0x7ffff7914930, args=<optimised out>, args@entry=0x7fffffffb650, nargs=nargs@entry=2, globals=globals@entry=0x7ffff79180f0) at Objects/call.c:283
#39 0x00005555555c9b88 in _PyFunction_FastCallDict (func=0x7ffff7920a70, args=0x7fffffffb650, nargs=2, kwargs=0x0) at Objects/call.c:322
#40 0x00005555555cb46e in object_vacall (callable=callable@entry=0x7ffff7920a70, vargs=vargs@entry=0x7fffffffb6b0) at Objects/call.c:1202
#41 0x00005555555cb705 in _PyObject_CallMethodIdObjArgs (obj=<optimised out>, name=name@entry=0x5555558386c0 <PyId__find_and_load.16947>) at Objects/call.c:1252
#42 0x0000555555695eaf in import_find_and_load (abs_name=0x7ffff6b7f8b0) at Python/import.c:1645
#43 PyImport_ImportModuleLevelObject (name=name@entry=0x7ffff6b7f8b0, globals=<optimised out>, locals=<optimised out>, fromlist=fromlist@entry=0x555555827dc0 <_Py_NoneStruct>, level=0) at Python/import.c:1757
#44 0x00005555555b78f7 in import_name (level=0x555555880680 <small_ints+160>, fromlist=0x555555827dc0 <_Py_NoneStruct>, name=0x7ffff6b7f8b0, f=0x555555d74080) at Python/ceval.c:4770
#45 _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:2600
#46 0x00005555556773f0 in PyEval_EvalFrameEx (throwflag=0, f=0x555555d74080) at Python/ceval.c:547
#47 _PyEval_EvalCodeWithName (_co=_co@entry=0x7ffff6b848a0, globals=globals@entry=0x7ffff6be98c0, locals=locals@entry=0x7ffff6be98c0, args=args@entry=0x0, argcount=argcount@entry=0, kwnames=kwnames@entry=0x0, kwargs=0x0, kwcount=0, 
    kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:3930
#48 0x0000555555677657 in PyEval_EvalCodeEx (closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwcount=0, kws=0x0, argcount=0, args=0x0, locals=0x7ffff6be98c0, globals=0x7ffff6be98c0, _co=0x7ffff6b848a0) at Python/ceval.c:3959
#49 PyEval_EvalCode (co=co@entry=0x7ffff6b848a0, globals=globals@entry=0x7ffff6be98c0, locals=locals@entry=0x7ffff6be98c0) at Python/ceval.c:524
#50 0x0000555555674c4d in builtin_exec_impl (module=<optimised out>, locals=0x7ffff6be98c0, globals=0x7ffff6be98c0, source=0x7ffff6b848a0) at Python/bltinmodule.c:1079
#51 builtin_exec (module=<optimised out>, args=<optimised out>, nargs=<optimised out>) at Python/clinic/bltinmodule.c.h:283
#52 0x00005555555ca9ac in _PyMethodDef_RawFastCallDict (method=0x555555836f40 <builtin_methods+480>, self=0x7ffff7966d10, args=0x7ffff6b7d158, nargs=2, kwargs=0x7ffff6be9eb0) at Objects/call.c:530
#53 0x00005555555cac06 in _PyCFunction_FastCallDict (kwargs=<optimised out>, nargs=<optimised out>, args=<optimised out>, func=0x7ffff796de10) at Objects/call.c:586
#54 PyCFunction_Call (kwargs=<optimised out>, args=<optimised out>, func=0x7ffff796de10) at Objects/call.c:791
#55 PyCFunction_Call (func=0x7ffff796de10, args=<optimised out>, kwargs=<optimised out>) at Objects/call.c:782
--Type <RET> for more, q to quit, c to continue without paging--c
#56 0x00005555555b8225 in do_call_core (kwdict=0x7ffff6be9eb0, callargs=0x7ffff6b7d140, func=0x7ffff796de10) at Python/ceval.c:4641
#57 _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3191
#58 0x00005555556773f0 in PyEval_EvalFrameEx (throwflag=0, f=0x555555d81260) at Python/ceval.c:547
#59 _PyEval_EvalCodeWithName (_co=_co@entry=0x7ffff790e150, globals=<optimised out>, locals=locals@entry=0x0, args=args@entry=0x555555c7ff00, argcount=3, kwnames=0x0, kwargs=0x555555c7ff18, kwcount=0, kwstep=1, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x7ffff790c300, qualname=0x7ffff790c300) at Python/ceval.c:3930
#60 0x00005555555c9c2d in _PyFunction_FastCallKeywords (func=<optimised out>, stack=0x555555c7ff00, nargs=<optimised out>, kwnames=<optimised out>) at Objects/call.c:433
#61 0x00005555555aff75 in call_function (pp_stack=pp_stack@entry=0x7fffffffbef0, oparg=<optimised out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4616
#62 0x00005555555b5dbb in _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3093
#63 0x00005555555aecd3 in function_code_fastcall (co=<optimised out>, args=<optimised out>, nargs=2, globals=<optimised out>) at Objects/call.c:283
#64 0x00005555555c9d42 in _PyFunction_FastCallKeywords (func=<optimised out>, stack=<optimised out>, nargs=<optimised out>, kwnames=<optimised out>) at Objects/call.c:415
#65 0x00005555555aff75 in call_function (pp_stack=pp_stack@entry=0x7fffffffc0d0, oparg=<optimised out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4616
#66 0x00005555555b119c in _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3110
#67 0x00005555555aecd3 in function_code_fastcall (co=<optimised out>, args=<optimised out>, nargs=1, globals=<optimised out>) at Objects/call.c:283
#68 0x00005555555c9d42 in _PyFunction_FastCallKeywords (func=<optimised out>, stack=<optimised out>, nargs=<optimised out>, kwnames=<optimised out>) at Objects/call.c:415
#69 0x00005555555aff75 in call_function (pp_stack=pp_stack@entry=0x7fffffffc2b8, oparg=<optimised out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4616
#70 0x00005555555b2ac9 in _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3124
#71 0x00005555555aecd3 in function_code_fastcall (co=<optimised out>, args=<optimised out>, nargs=2, globals=<optimised out>) at Objects/call.c:283
#72 0x00005555555c9d42 in _PyFunction_FastCallKeywords (func=<optimised out>, stack=<optimised out>, nargs=<optimised out>, kwnames=<optimised out>) at Objects/call.c:415
#73 0x00005555555aff75 in call_function (pp_stack=pp_stack@entry=0x7fffffffc498, oparg=<optimised out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4616
#74 0x00005555555b2ac9 in _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3124
#75 0x00005555555aecd3 in function_code_fastcall (co=co@entry=0x7ffff7914930, args=<optimised out>, args@entry=0x7fffffffc630, nargs=nargs@entry=2, globals=globals@entry=0x7ffff79180f0) at Objects/call.c:283
#76 0x00005555555c9b88 in _PyFunction_FastCallDict (func=0x7ffff7920a70, args=0x7fffffffc630, nargs=2, kwargs=0x0) at Objects/call.c:322
#77 0x00005555555cb46e in object_vacall (callable=callable@entry=0x7ffff7920a70, vargs=vargs@entry=0x7fffffffc690) at Objects/call.c:1202
#78 0x00005555555cb705 in _PyObject_CallMethodIdObjArgs (obj=<optimised out>, name=name@entry=0x5555558386c0 <PyId__find_and_load.16947>) at Objects/call.c:1252
#79 0x0000555555695eaf in import_find_and_load (abs_name=0x7ffff6beebb0) at Python/import.c:1645
#80 PyImport_ImportModuleLevelObject (name=name@entry=0x7ffff6beebb0, globals=<optimised out>, locals=<optimised out>, fromlist=fromlist@entry=0x555555827dc0 <_Py_NoneStruct>, level=0) at Python/import.c:1757
#81 0x00005555555b78f7 in import_name (level=0x555555880680 <small_ints+160>, fromlist=0x555555827dc0 <_Py_NoneStruct>, name=0x7ffff6beebb0, f=0x7ffff649f3d0) at Python/ceval.c:4770
#82 _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:2600
#83 0x00005555556773f0 in PyEval_EvalFrameEx (throwflag=0, f=0x7ffff649f3d0) at Python/ceval.c:547
#84 _PyEval_EvalCodeWithName (_co=_co@entry=0x7ffff6b84780, globals=globals@entry=0x7ffff647e050, locals=locals@entry=0x7ffff647e050, args=args@entry=0x0, argcount=argcount@entry=0, kwnames=kwnames@entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:3930
#85 0x0000555555677657 in PyEval_EvalCodeEx (closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwcount=0, kws=0x0, argcount=0, args=0x0, locals=0x7ffff647e050, globals=0x7ffff647e050, _co=0x7ffff6b84780) at Python/ceval.c:3959
#86 PyEval_EvalCode (co=co@entry=0x7ffff6b84780, globals=globals@entry=0x7ffff647e050, locals=locals@entry=0x7ffff647e050) at Python/ceval.c:524
#87 0x0000555555674c4d in builtin_exec_impl (module=<optimised out>, locals=0x7ffff647e050, globals=0x7ffff647e050, source=0x7ffff6b84780) at Python/bltinmodule.c:1079
#88 builtin_exec (module=<optimised out>, args=<optimised out>, nargs=<optimised out>) at Python/clinic/bltinmodule.c.h:283
#89 0x00005555555ca9ac in _PyMethodDef_RawFastCallDict (method=0x555555836f40 <builtin_methods+480>, self=0x7ffff7966d10, args=0x7ffff6b73fb8, nargs=2, kwargs=0x7ffff564dbe0) at Objects/call.c:530
#90 0x00005555555cac06 in _PyCFunction_FastCallDict (kwargs=<optimised out>, nargs=<optimised out>, args=<optimised out>, func=0x7ffff796de10) at Objects/call.c:586
#91 PyCFunction_Call (kwargs=<optimised out>, args=<optimised out>, func=0x7ffff796de10) at Objects/call.c:791
#92 PyCFunction_Call (func=0x7ffff796de10, args=<optimised out>, kwargs=<optimised out>) at Objects/call.c:782
#93 0x00005555555b8225 in do_call_core (kwdict=0x7ffff564dbe0, callargs=0x7ffff6b73fa0, func=0x7ffff796de10) at Python/ceval.c:4641
#94 _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3191
#95 0x00005555556773f0 in PyEval_EvalFrameEx (throwflag=0, f=0x7ffff55bb3d0) at Python/ceval.c:547
#96 _PyEval_EvalCodeWithName (_co=_co@entry=0x7ffff790e150, globals=<optimised out>, locals=locals@entry=0x0, args=args@entry=0x7ffff6b773b0, argcount=3, kwnames=0x0, kwargs=0x7ffff6b773c8, kwcount=0, kwstep=1, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x7ffff790c300, qualname=0x7ffff790c300) at Python/ceval.c:3930
#97 0x00005555555c9c2d in _PyFunction_FastCallKeywords (func=<optimised out>, stack=0x7ffff6b773b0, nargs=<optimised out>, kwnames=<optimised out>) at Objects/call.c:433
#98 0x00005555555aff75 in call_function (pp_stack=pp_stack@entry=0x7fffffffced0, oparg=<optimised out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4616
#99 0x00005555555b5dbb in _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3093
#100 0x00005555555aecd3 in function_code_fastcall (co=<optimised out>, args=<optimised out>, nargs=2, globals=<optimised out>) at Objects/call.c:283
#101 0x00005555555c9d42 in _PyFunction_FastCallKeywords (func=<optimised out>, stack=<optimised out>, nargs=<optimised out>, kwnames=<optimised out>) at Objects/call.c:415
#102 0x00005555555aff75 in call_function (pp_stack=pp_stack@entry=0x7fffffffd0b0, oparg=<optimised out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4616
#103 0x00005555555b119c in _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3110
#104 0x00005555555aecd3 in function_code_fastcall (co=<optimised out>, args=<optimised out>, nargs=1, globals=<optimised out>) at Objects/call.c:283
#105 0x00005555555c9d42 in _PyFunction_FastCallKeywords (func=<optimised out>, stack=<optimised out>, nargs=<optimised out>, kwnames=<optimised out>) at Objects/call.c:415
#106 0x00005555555aff75 in call_function (pp_stack=pp_stack@entry=0x7fffffffd298, oparg=<optimised out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4616
#107 0x00005555555b2ac9 in _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3124
#108 0x00005555555aecd3 in function_code_fastcall (co=<optimised out>, args=<optimised out>, nargs=2, globals=<optimised out>) at Objects/call.c:283
#109 0x00005555555c9d42 in _PyFunction_FastCallKeywords (func=<optimised out>, stack=<optimised out>, nargs=<optimised out>, kwnames=<optimised out>) at Objects/call.c:415
#110 0x00005555555aff75 in call_function (pp_stack=pp_stack@entry=0x7fffffffd478, oparg=<optimised out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4616
#111 0x00005555555b2ac9 in _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3124
#112 0x00005555555aecd3 in function_code_fastcall (co=co@entry=0x7ffff7914930, args=<optimised out>, args@entry=0x7fffffffd610, nargs=nargs@entry=2, globals=globals@entry=0x7ffff79180f0) at Objects/call.c:283
#113 0x00005555555c9b88 in _PyFunction_FastCallDict (func=0x7ffff7920a70, args=0x7fffffffd610, nargs=2, kwargs=0x0) at Objects/call.c:322
#114 0x00005555555cb46e in object_vacall (callable=callable@entry=0x7ffff7920a70, vargs=vargs@entry=0x7fffffffd670) at Objects/call.c:1202
#115 0x00005555555cb705 in _PyObject_CallMethodIdObjArgs (obj=<optimised out>, name=name@entry=0x5555558386c0 <PyId__find_and_load.16947>) at Objects/call.c:1252
#116 0x0000555555695eaf in import_find_and_load (abs_name=0x7ffff7743c30) at Python/import.c:1645
#117 PyImport_ImportModuleLevelObject (name=name@entry=0x7ffff7743c30, globals=<optimised out>, locals=<optimised out>, fromlist=fromlist@entry=0x7ffff77db410, level=0) at Python/import.c:1757
#118 0x00005555555b78f7 in import_name (level=0x555555880680 <small_ints+160>, fromlist=0x7ffff77db410, name=0x7ffff7743c30, f=0x7ffff787d450) at Python/ceval.c:4770
#119 _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:2600
#120 0x00005555556773f0 in PyEval_EvalFrameEx (throwflag=0, f=0x7ffff787d450) at Python/ceval.c:547
#121 _PyEval_EvalCodeWithName (_co=_co@entry=0x7ffff77c05d0, globals=globals@entry=0x0, locals=locals@entry=0x7ffff78e6d20, args=args@entry=0x0, argcount=argcount@entry=0, kwnames=kwnames@entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:3930
#122 0x0000555555677657 in PyEval_EvalCodeEx (closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwcount=0, kws=0x0, argcount=0, args=0x0, locals=0x7ffff78e6d20, globals=0x0, _co=0x7ffff77c05d0) at Python/ceval.c:3959
#123 PyEval_EvalCode (co=co@entry=0x7ffff77c05d0, globals=globals@entry=0x7ffff78e6d20, locals=locals@entry=0x7ffff78e6d20) at Python/ceval.c:524
#124 0x00005555556ae265 in run_mod (arena=0x7ffff78fc7b0, flags=0x7fffffffdb10, locals=0x7ffff78e6d20, globals=0x7ffff78e6d20, filename=0x7ffff76ca9d0, mod=0x5555559944b8) at Python/pythonrun.c:1035
#125 PyRun_FileExFlags (fp=<optimised out>, filename_str=<optimised out>, start=<optimised out>, globals=0x7ffff78e6d20, locals=0x7ffff78e6d20, closeit=1, flags=0x7fffffffdb10) at Python/pythonrun.c:988
#126 0x00005555556ae3ff in PyRun_SimpleFileExFlags (fp=fp@entry=0x5555558a1310, filename=<optimised out>, closeit=closeit@entry=1, flags=flags@entry=0x7fffffffdb10) at Python/pythonrun.c:429
#127 0x00005555556ae89c in PyRun_AnyFileExFlags (fp=fp@entry=0x5555558a1310, filename=<optimised out>, closeit=closeit@entry=1, flags=flags@entry=0x7fffffffdb10) at Python/pythonrun.c:84
#128 0x00005555555be76e in pymain_run_file (p_cf=0x7fffffffdb10, filename=<optimised out>, fp=0x5555558a1310) at Modules/main.c:427
#129 pymain_run_filename (cf=0x7fffffffdb10, pymain=0x7fffffffdc20) at Modules/main.c:1606
#130 pymain_run_python (pymain=0x7fffffffdc20) at Modules/main.c:2867
#131 pymain_main (pymain=pymain@entry=0x7fffffffdc20) at Modules/main.c:3028
#132 0x00005555555be9bd in _Py_UnixMain (argc=<optimised out>, argv=<optimised out>) at Modules/main.c:3063
#133 0x00007ffff7c631e3 in __libc_start_main (main=0x5555555aec60 <main>, argc=4, argv=0x7fffffffdd78, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7fffffffdd68) at ../csu/libc-start.c:308
#134 0x00005555555b86de in _start () at Objects/call.c:287
```

**Comment by dashko** [comment]
Bump

**Comment by dashko** [comment]
I have the same issue:
python 3.6.10 on Ubuntu 20.04 LTS
