### ISSUE TITLE
"pip3 install pyhash" Fails on Fedora 35

### ISSUE THREAD

**Issue by pazooki** [flier/pyfasthash#60]
`$ pip3 install pyhash
Defaulting to user installation because normal site-packages is not writeable
Collecting pyhash
  Using cached pyhash-0.9.3.tar.gz (602 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      /home/mehrdadpazooki/.local/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/py-cpuinfo/
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [6 lines of output]
            usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
               or: setup.py --help [cmd1 cmd2 ...]
               or: setup.py --help-commands
               or: setup.py cmd --help
      
            error: invalid command 'bdist_wheel'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for py-cpuinfo
      ERROR: Failed to build one or more wheels
      Traceback (most recent call last):
        File "/home/mehrdadpazooki/.local/lib/python3.10/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/usr/lib64/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpud_x_6gl', '--quiet', 'py-cpuinfo']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-hdfy4j4s/pyhash_3ebba8e651b640ac8f60b2263d8e814d/setup.py", line 129, in <module>
          setup(name='pyhash',
        File "/home/mehrdadpazooki/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 78, in setup
          _install_setup_requires(attrs)
        File "/home/mehrdadpazooki/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 72, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/home/mehrdadpazooki/.local/lib/python3.10/site-packages/setuptools/dist.py", line 843, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/home/mehrdadpazooki/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 777, in resolve
          dist = best[req.key] = env.best_match(
        File "/home/mehrdadpazooki/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1062, in best_match
          return self.obtain(req, installer)
        File "/home/mehrdadpazooki/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1074, in obtain
          return installer(requirement)
        File "/home/mehrdadpazooki/.local/lib/python3.10/site-packages/setuptools/dist.py", line 923, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/home/mehrdadpazooki/.local/lib/python3.10/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpud_x_6gl', '--quiet', 'py-cpuinfo']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

**Comment by pazooki** [comment]
Now I'm getting this error:

```
$ pip3 install --force-reinstall --ignore-installed --no-binary :all: pyhash
Defaulting to user installation because normal site-packages is not writeable
Collecting pyhash
  Using cached pyhash-0.9.3.tar.gz (602 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      /home/mehrdadpazooki/.local/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
      error in pyhash setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by pazooki** [comment]
Resolved!
```
ip3 install setuptools==58
```

**Comment by pazooki** [comment]
Resolved!
```
pip3 install setuptools==58
```
