### ISSUE TITLE
 python setup.py egg_info did not run successfully.

### ISSUE THREAD

**Issue by sodothis** [flier/pyfasthash#72]
"
        File "<frozen ntpath>", line 108, in join
      TypeError: expected str, bytes or os.PathLike object, not NoneType
      [end of output]
"

**Comment by Wiley-Black** [comment]
Also seeing this.

```console
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\x\AppData\Local\Temp\pip-install-gs5j2lzl\pyhash_31f60d50f6c9438c9a0ebba6c65d72b8\setup.py", line 38, in <module>
          os.path.join(os.environ.get('PYTHON_HOME'), 'include'),
        File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 104, in join
          path = os.fspath(path)
      TypeError: expected str, bytes or os.PathLike object, not NoneType
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

Platform is Windows 11, Python 3.10.  Operating in a virtual environment.
